spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_manager
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        javax.persistence.validation.mode: none
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: usermanagert@gmail.com
    password: mdrb yfhj eara zvkl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
